# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgres-{{.Replica}}-{{.Iteration}}
spec:
  template:
    metadata:
      labels:
        name: postgres-{{.Replica}}-{{.Iteration}}
    spec:
      {{ if hasKey . "nodeSelector" }}
      nodeSelector:
        kubernetes.io/hostname: "{{ .nodeSelector }}"
      {{ end }}
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
      containers:
      - name: postgresql
        # image: registry.access.redhat.com/rhscl/postgresql-10-rhel7:latest
        image: postgres:10
        ports:
        - containerPort: 5432
          protocol: TCP
        env:
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: secret
        - name: POSTGRES_DB
          value: kubelet-density
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
      restartPolicy: Always
  replicas: 1
  selector:
    matchLabels:
      name: postgres-{{.Replica}}-{{.Iteration}}
  strategy:
    type: RollingUpdate
