services:
  opensearch-node1:
    image: registry.sighup.io/fury/opensearchproject/opensearch:2.19.1
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - plugins.security.disabled=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Pa%%w0rd!
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    expose:
      - "9200"
  # optional - uncomment if you want to explore raw data from OpenSearch
  # opensearch-dashboards:
  #   image: registry.sighup.io/fury/opensearchproject/opensearch-dashboards:2.19.1
  #   container_name: opensearch-dashboards
  #   environment:
  #     - OPENSEARCH_HOSTS=["http://opensearch-node1:9200"]
  #   command:
  #     - /bin/sh
  #     - -c
  #     - |
  #       ./bin/opensearch-dashboards-plugin remove securityDashboards || true ; opensearch-dashboards
  #   ports:
  #     - "5601:5601"
  #   depends_on:
  #     - opensearch-node1

  grafana:
    image: registry.sighup.io/fury/grafana/grafana:12.1.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - opensearch-node1
volumes:
  opensearch-data:
